// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlrlobigcfxhsjvbeemu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpscmxvYmlnY2Z4aHNqdmJlZW11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMTE1NTMsImV4cCI6MjA2Mjg4NzU1M30.hZFdxHq5i35FsPLs8sEaAhx5OzpQG9700ZDvxWNL184";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);